### ISSUE TITLE
tomowallet chush when trying to send tomos

### ISSUE THREAD

**Issue by freinaba** [tomochain/tomowallet#18]
**Describe the bug**
tomowallet crash when trying to send tomos

**To Reproduce**
1. Click on QR code on the tomowallet
2. Click on "enter a recipient address"
and tomowallet crashes

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Device specification (please complete the following information):**
 - Device: Samsung Galaxy S7 edge]
 - TomoWallet version [V0.14.1]

**Comment by vtproduction** [comment]
fixed at version 0.14.4

**Comment by freinaba** [comment]
Update perfectly corrected the issue! thanks Lê Mạnh Niên!
