### ISSUE TITLE
Cannot log in into Tomomaster using mobile wallet QR

### ISSUE THREAD

**Issue by freinaba** [tomochain/tomowallet#19]
**Describe the bug**
Cannot log in into Tomomaster using mobile wallet QR

**To Reproduce**
1. click on QR symbol in tomowallet
2. put camera in front of the log in QR code of the tomomaster log in page
3. pic is done and image get blocked but tomomaster does not log in

**Device specification (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S7 edge]

 - TomoWallet version [e.g. V0.14.1]

**Comment by vtproduction** [comment]
fixed at version 0.14.4

**Comment by freinaba** [comment]
Update perfectly corrected the issue! thanks Lê Mạnh Niên!
