### ISSUE TITLE
Resigning action returns propose successful screen.

### ISSUE THREAD

**Issue by pqv199x** [tomochain/tomowallet#2]
**Describe the bug**
Resigning action returns propose successful screen.

**To Reproduce**
1. Go to https://master.devnet.tomochain.com/
2. Go to an owned masternode
3. Click resign button
4. Confirm and scan the QR code with tomowallet

**Expected behavior**
A confirmation screen for resigning a masternode

**Actual behavior**
'Propose successful' screen showed up

**Device specification (please complete the following information):**
 - Device: [Samsung phone]
 - OS: [Android]
 - TomoWallet version [0.8]

**Additional context**

**Comment by vtproduction** [comment]
fixed at release 0.8.4
