### ISSUE TITLE
Error when trying to send tomos

### ISSUE THREAD

**Issue by freinaba** [tomochain/tomowallet#20]
Description of the error:
When sending tomos from Mobile wallet AND ONLY WHEN ADDING A TEXT MESSAGE I get this error message
![Screenshot_20200912-202838_Gallery](https://user-images.githubusercontent.com/70858578/93002336-a300d000-f536-11ea-973d-dfc455b663b2.jpg)

It seems like if tomo confuse the transaction with eth transaction, although tomochain is selected

* Device specification (please complete the following information):
Device: [e.g. Samsung Galaxy S7 edge]
TomoWallet version [e.g. V0.14.5]

**Comment by freinaba** [comment]
Same problem confirmed on tomowallet V0.14.5 in a Samsung A7 2018

**Comment by thanhson1085** [comment]
Thank you for the report. @vtproduction will investigate it.

**Comment by vtproduction** [comment]
Fixed at version 0.14.6
